markdown: redcarpet
highlighter: rouge

name: toxinu
title: toxinu
description: "Developer, hacker, music listener and books reader."
url: https://toxi.nu
github: toxinu
twitter: toxinu_
google-plus:
google-site-verification:
# Can be gravatar url (https://secure.gravatar.com/avatar/5218a2cef79f166d20e55b60c48f97a0?s=36&d=identicon)
include: []

projects:

- title: Sublimall
  url:   https://github.com/toxinu/Sublimall
  desc:  SublimeText 3 plugin to sync your configuration.
  tech:  Python
  stars:  550

- title: Pyhn
  url:   https://github.com/toxinu/pyhn
  desc:  Hacker News command line client.
  tech:  Python / Ncurses
  stars: 330

- title: Leselys
  url:   https://github.com/toxinu/leselys
  desc:  Web based RSS reader.
  tech:  Python / Flask
  stars: 200

- title: Isit
  url:   https://github.com/toxinu/isit
  desc:  Python environment discoverer.
  tech:  Python

- title: Minne
  url:   https://github.com/toxinu/minne
  desc:  Links aggregator.
  tech:  Python / Django
